name: Deployment Pipeline

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    branches:
      - "*"

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
    
  prettierFormatCheck:
    name: Prettier Format Check
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Check Prettier issues
        run: npm run prettier:check
    
  build:
    name: Build File
    runs-on: ubuntu-latest
    needs: [prettierFormatCheck]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: [prettierFormatCheck]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Vercel Cli
        run: npm install --global vercel@latest
      - name: Pull vercel Environment
        run: vercel pull --yes --environment=preview --token=${{secrets.VERCEL_TOKEN}}
      - name: Build Vercel Artifacts
        run: vercel build --token=${{secrets.VERCEL_TOKEN}}
      - name: Deploy Artifacts
        run: vercel deploy --prebuild --token=${{secrets.VERCEL_TOKEN}}
    